version: "3.8"

services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskmanagement
    ports:
      - "5432:5432"
    #volumes:
    #  - /home/taskmanagement/postgresql/data:/var/lib/postgresql/data

  server:
    build: .
    container_name: taskmanagement_server
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/taskmanagement
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - postgres
   