CREATE TABLE public.users
(
    id         int8         NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
    created_at timestamp(6) NULL,
    created_by varchar(255) NULL,
    updated_at timestamp(6) NULL,
    updated_by varchar(255) NULL,
    full_name  varchar(255) NULL,
    username   varchar(255) NULL,
    password   varchar(255) NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);