CREATE TABLE public.task
(
    id          int8         NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
    created_at  timestamp(6) NULL,
    created_by  varchar(255) NULL,
    updated_at  timestamp(6) NULL,
    updated_by  varchar(255) NULL,
    description varchar(255) NULL,
    title       varchar(255) NULL,
    category    int4         NOT NULL,
    category_id int8         NULL,
    status      int4         NOT NULL,
    user_id     int8         NULL,
    CONSTRAINT task_pkey PRIMARY KEY (id)
);

CREATE TABLE public.bug
(
    id                 int8         NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
    created_at         timestamp(6) NULL,
    created_by         varchar(255) NULL,
    updated_at         timestamp(6) NULL,
    updated_by         varchar(255) NULL,
    severity           int4         NOT NULL,
    steps_to_reproduce varchar(255) NULL,
    actual_result      varchar(255) NULL,
    expected_result    varchar(255) NULL,
    CONSTRAINT bug_pkey PRIMARY KEY (id)
);

CREATE TABLE public.feature
(
    id             int8         NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
    created_at     timestamp(6) NULL,
    created_by     varchar(255) NULL,
    updated_at     timestamp(6) NULL,
    updated_by     varchar(255) NULL,
    business_value varchar(255) NULL,
    deadline       timestamp(6) NULL,
    CONSTRAINT feature_pkey PRIMARY KEY (id)
);

